first_name = input("Hello. What's your name? Type your first name and press enter.")
print ("Hi {}! Let's play a game.".format(first_name))
adjective1 = input("Type an adjective, and press enter.")
noun1 = input("Type a noun(plural), and press enter.")
noun2 = input("Type another noun(plural), and press enter.")
adjective2 = input("Type another adjective, and press enter.")
print ("Bears are {}.".format(adjective1))
print ("{} are too.".format(noun1))
print ("{} are {}.".format(noun2, adjective2))
print ("And so are you!")
